package io.github.darlene.leakdetectionapplication.alert;

import io.github.darlene.leakdetectionapplication.alert.*;
import io.github.darlene.leakdetectionapplication.analytics.*;
import io.github.darlene.leakdetectionapplication.auth.*;
import io.github.darlene.leakdetectionapplication.configuration.*;
import io.github.darlene.leakdetectionapplication.messaging.*;
import io.github.darlene.leakdetectionapplication.monitoring.*;
import io.github.darlene.leakdetectionapplication.pipeline.*;
import io.github.darlene.leakdetectionapplication.recommendation.*;
import io.github.darlene.leakdetectionapplication.sensor.*;
import io.github.darlene.leakdetectionapplication.simulation.*;
import io.github.darlene.leakdetectionapplication.shared.*;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import java.util.List;
import io.github.darlene.leakdetectionapplication.alert.FaultAlert;
import io.github.darlene.leakdetectionapplication.alert.FaultAlertResponse;
import io.github.darlene.leakdetectionapplication.monitoring.SystemStatus;

/**
 * Mapper interface for converting FaultAlert entities to response DTOs.
 * Handles enum to String conversion and nested object field extraction.
 * Implementation is generated by MapStruct at compile time.
 */

@Mapper(componentModel = "spring")
public interface FaultAlertMapper {

    /**
     * Converts a single FaultAlert entity to a FaultAlertResponse DTO.
     * Extracts fault class name, description, severity level, severity description,
     * color code, and timestamp from nested and enum fields.
     */

    @Mapping(target = "faultClass", expression = "java(entity.getFaultClass().name())")
    @Mapping(target = "faultDescription", expression = "java(entity.getFaultClass().getDescription())")
    @Mapping(target = "severityLevel", expression = "java(entity.getSeverityLevel().name())")
    @Mapping(target = "severityDescription", expression = "java(entity.getSeverityLevel().getDescription())")
    @Mapping(target = "readingTime", source = "sensorReading.readingTime")
    @Mapping(target = "colorCode", expression = "java(resolveColorCode(entity))")

    FaultAlertResponse toResponse(FaultAlert entity);
    /**
     * Converts a list of FaultAlert entities to a list of FaultAlertResponse DTOs.
     */
    List<FaultAlertResponse> toResponseList(List<FaultAlert> entity);

    default String resolveColorCode(FaultAlert entity){
        return switch (entity.getFaultClass()){
            case LEAK -> SystemStatus.LEAK_DETECTED.getColorCode();
            case BLOCKAGE -> SystemStatus.BLOCKAGE_DETECTED.getColorCode();
            default -> SystemStatus.NORMAL.getColorCode();
        };
    }
}