package io.github.darlene.leakdetectionapplication.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import java.util.List;
import io.github.darlene.leakdetectionapplication.domain.FaultAlert;
import io.github.darlene.leakdetectionapplication.dto.response.FaultAlertResponse;
import io.github.darlene.leakdetectionapplication.domain.SystemStatus;

/**
 * Mapper interface for converting FaultAlert entities to response DTOs.
 * Handles enum to String conversion and nested object field extraction.
 * Implementation is generated by MapStruct at compile time.
 */

@Mapper(componentModel = "spring")
public interface FaultAlertMapper {

    /**
     * Converts a single FaultAlert entity to a FaultAlertResponse DTO.
     * Extracts fault class name, description, severity level, severity description,
     * color code, and timestamp from nested and enum fields.
     */

    @Mapping(target = "faultClass", expression = "java(entity.getFaultClass().name())")
    @Mapping(target = "faultDescription", expression = "java(entity.getFaultClass().getDescription())")
    @Mapping(target = "severityLevel", expression = "java(entity.getSeverityLevel().name())")
    @Mapping(target = "severityDescription", expression = "java(entity.getSeverityLevel().getDescription())")
    @Mapping(target = "timestamp", source = "sensorReading.timestamp")
    @Mapping(target = "colorCode", expression = "java(resolveColorCode(entity))")

    FaultAlertResponse toResponse(FaultAlert entity);
    /**
     * Converts a list of FaultAlert entities to a list of FaultAlertResponse DTOs.
     */
    List<FaultAlertResponse> toResponseList(List<FaultAlert> entity);

    default String resolveColorCode(FaultAlert entity){
        return switch (entity.getFaultClass()){
            case LEAK -> SystemStatus.LEAK_DETECTED.getColorCode();
            case BLOCKAGE -> SystemStatus.BLOCKAGE_DETECTED.getColorCode();
            default -> SystemStatus.NORMAL.getColorCode();
        };
    }
}