package io.github.darlene.leakdetectionapplication.mapper;

import org.mapstruct.Mapper;
import java.util.List;
import io.github.darlene.leakdetectionapplication.domain.SensorReading;
import io.github.darlene.leakdetectionapplication.dto.response.SensorReadingResponse;

/**
 * Mapper interface for converting SensorReading entities to response DTOs.
 * All field mappings are automatic — entity and response field names match.
 * Implementation is generated by MapStruct at compile time.
 */
@Mapper(componentModel = "spring")
public interface SensorReadingMapper {

    SensorReadingResponse toResponse(SensorReading entity);

    List<SensorReadingResponse> toResponseList(List<SensorReading> entities);
}