spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    io.github.darlene: INFO

server:
  error:
    include-message: never
    include-stacktrace: never

mqtt:
  broker-url: tcp://mosquitto:1883

ml-service:
  base-url: http://ml-service:5000

ollama:
  base-url: http://ollama:11434
  model: llama3