jwt.secret=vYgewI1eYRBaCVZMF0ZCW9le/IFewfbowpmtkYYBAg4=
jwt.expiration-ms=3600000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000