mqtt.broker=ssl://7b84d3b2af6245bbb13d4c3f4b745257.s1.eu.hivemq.cloud:8883
mqtt.clientId=JavaSpringClient
mqtt.username=leakdetection
mqtt.password=Nasimiyu12345
mqtt.subscribe.topics=pipeline/devices/register,pipeline/sensors/+/node,pipeline/sensors/+/status,pipeline/sensors/+/diagnostic
mqtt.publish.topic.config=pipeline/devices/%s/config
mqtt.publish.topic.alerts=pipeline/alerts/%s
mqtt.publish.topic.commands=pipeline/commands/%s
mqtt.cleanSession=true
mqtt.connectionTimeout=30
mqtt.keepAliveInterval=60