
mqtt.broker=ssl://7b84d3b2af6245bbb13d4c3f4b745257.s1.eu.hivemq.cloud:8883
mqtt.clientId=JavaSpringClient
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}
mqtt.cleanSession=true
mqtt.connectionTimeout=30
mqtt.keepAliveInterval=60
mqtt.qos=1

mqtt.subscribe.topics=pipeline/devices/register,pipeline/sensors/+/node,pipeline/sensors/+/status,pipeline/sensors/+/diagnostic

mqtt.topics.sensor-data=pipeline/sensors/node
mqtt.topics.heartbeat=pipeline/heartbeat

mqtt.topics.led-status=pipeline/led/status
mqtt.topics.cmd-scenario=pipeline/command/scenario
mqtt.topics.system-status=pipeline/status/system
mqtt.topics.new-alert=pipeline/alerts/new

mqtt.publish.topic.config=pipeline/devices/%s/config
mqtt.publish.topic.alerts=pipeline/alerts/%s
mqtt.publish.topic.commands=pipeline/commands/%s